<a href="https://colab.research.google.com/github/Gabriela07-b/ESTADISTICA-/blob/main/Taller_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 NumPy y Pandas para Ciencia de Datos


#  PARTE 1: NumPy — Arreglos Numéricos

In [1]:
import numpy as np

## 1.1 Creación de arreglos con `np.array()`

Un arreglo NumPy (ndarray) es la estructura de datos base de la biblioteca. A diferencia de una lista de Python, todos sus elementos son del **mismo tipo** y las operaciones matemáticas se aplican elemento a elemento (vectorización), lo que lo hace mucho más eficiente.

In [2]:
# Arreglo 1D: temperaturas registradas en una semana (°C)
temperaturas = np.array([18.5, 22.0, 19.3, 25.1, 23.7, 20.0, 17.8])

# Arreglo 2D: tabla de calificaciones (3 estudiantes, 4 materias)
notas = np.array([[4.2, 3.8, 4.5, 3.0],
                  [3.5, 4.0, 3.9, 4.7],
                  [4.8, 4.1, 3.6, 4.3]])

print("Temperaturas semana:", temperaturas)
print("\nTabla de notas (3 estudiantes x 4 materias):")
print(notas)

Temperaturas semana: [18.5 22.  19.3 25.1 23.7 20.  17.8]

Tabla de notas (3 estudiantes x 4 materias):
[[4.2 3.8 4.5 3. ]
 [3.5 4.  3.9 4.7]
 [4.8 4.1 3.6 4.3]]


## 1.2 Operaciones aritméticas sobre arreglos

En NumPy las operaciones como `*`, `+`, `-` se aplican **elemento a elemento** (no como en listas de Python donde `*` repite). Esto refleja el comportamiento matemático de vectores y matrices.

In [4]:
# Convertir temperaturas de Celsius a Fahrenheit: F = C * 9/5 + 32
temps_f = temperaturas * 9/5 + 32
print("Temperaturas en Fahrenheit:", temps_f)

# Diferencia entre dos arreglos
pesos_antes = np.array([70, 85, 62, 90, 75])
pesos_despues = np.array([67, 82, 60, 88, 72])
diferencia = pesos_antes - pesos_despues
print("\nKilos perdidos por persona:", diferencia)

Temperaturas en Fahrenheit: [65.3  71.6  66.74 77.18 74.66 68.   64.04]

Kilos perdidos por persona: [3 3 2 2 3]


## 1.3 Atributos: `.shape`, `.ndim`, `.dtype`, `.size`

Estos atributos permiten **inspeccionar la estructura** de un arreglo:
- `.shape` → dimensiones (filas, columnas)
- `.ndim` → número de dimensiones
- `.dtype` → tipo de dato de los elementos
- `.size` → total de elementos

In [5]:
print("Shape de notas:", notas.shape)     # 3 filas, 4 columnas
print("Dimensiones:", notas.ndim)          # 2D
print("Tipo de dato:", notas.dtype)        # float64
print("Total de elementos:", notas.size)   # 12

Shape de notas: (3, 4)
Dimensiones: 2
Tipo de dato: float64
Total de elementos: 12


## 1.4 Arreglos especiales: `np.zeros()`, `np.ones()`, `np.eye()`

Son funciones de **inicialización** muy útiles:
- `np.zeros()` → matriz llena de ceros (p.ej., para inicializar parámetros de un modelo)
- `np.ones()` → matriz llena de unos
- `np.eye()` → matriz identidad (fundamental en álgebra lineal)

In [6]:
# Matriz de ceros: 4 sensores x 6 mediciones (aún sin datos)
sensor_data = np.zeros((4, 6))
print("Matriz de ceros (4x6):")
print(sensor_data)

# Matriz de unos: útil para crear máscaras
mascara = np.ones((2, 5))
print("\nMatriz de unos (2x5):")
print(mascara)

# Matriz identidad 3x3
identidad = np.eye(3)
print("\nMatriz identidad (3x3):")
print(identidad)

Matriz de ceros (4x6):
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Matriz de unos (2x5):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matriz identidad (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 1.5 Secuencias: `np.arange()` y `np.linspace()`

- `np.arange(inicio, fin, paso)` → secuencia con paso fijo (equivalente a `range` pero para arrays)
- `np.linspace(inicio, fin, n)` → `n` valores **igualmente espaciados** entre inicio y fin. Muy usado para graficar funciones matemáticas.

In [7]:
# Horas del día cada 4 horas
horas = np.arange(0, 24, 4)
print("Horas registradas:", horas)

# 8 puntos equidistantes entre 0 y 1 (para evaluar una función)
puntos = np.linspace(0, 1, 8)
print("Puntos para evaluar función:", puntos)

Horas registradas: [ 0  4  8 12 16 20]
Puntos para evaluar función: [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


## 1.6 Indexación y slicing

Permite acceder a elementos específicos o subconjuntos del arreglo. En arreglos 2D se usa `[fila, columna]`. El slice `[inicio:fin]` toma desde `inicio` hasta `fin-1`.

In [8]:
ventas = np.array([120, 340, 210, 450, 380, 290, 500])

print("Primera venta:", ventas[0])
print("Última venta:", ventas[-1])
print("Ventas del martes al jueves (índices 1 a 3):", ventas[1:4])

# Indexación en 2D
print("\nNota del estudiante 2, materia 3:", notas[1, 2])  # fila 1, columna 2
print("Todas las notas de la materia 1 (columna 0):", notas[:, 0])

Primera venta: 120
Última venta: 500
Ventas del martes al jueves (índices 1 a 3): [340 210 450]

Nota del estudiante 2, materia 3: 3.9
Todas las notas de la materia 1 (columna 0): [4.2 3.5 4.8]


## 1.7 Producto de Hadamard y `np.dot()`

- **Producto de Hadamard** (`*`): multiplica elemento a elemento. Útil para aplicar pesos a variables.
- **`np.dot()`**: producto matricial estándar (suma de productos). Fundamental en redes neuronales y regresión lineal.

In [9]:
precio = np.array([15000, 8000, 22000])   # precio por unidad
cantidad = np.array([3, 10, 2])            # unidades vendidas

# Hadamard: ingreso por producto
ingresos = precio * cantidad
print("Ingresos por producto:", ingresos)

# Producto matricial
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("\nProducto matricial A·B:")
print(np.dot(A, B))

Ingresos por producto: [45000 80000 44000]

Producto matricial A·B:
[[19 22]
 [43 50]]


## 1.8 Estadísticas descriptivas

NumPy ofrece funciones estadísticas eficientes: `mean`, `median`, `std`, `sum`, `min`, `max`. Son la base del análisis exploratorio de datos (EDA).

In [10]:
edades = np.array([22, 35, 28, 41, 19, 30, 27, 45, 33])

print(f"Media:    {np.mean(edades):.2f}")
print(f"Mediana:  {np.median(edades):.2f}")
print(f"Desv.Std: {np.std(edades):.2f}")
print(f"Suma:     {np.sum(edades)}")
print(f"Mínimo:   {np.min(edades)}")
print(f"Máximo:   {np.max(edades)}")

Media:    31.11
Mediana:  30.00
Desv.Std: 7.94
Suma:     280
Mínimo:   19
Máximo:   45


## 1.9 Manipulación: `.reshape()`, `.flatten()`, `np.concatenate()`

- `.reshape(f, c)` → cambia la forma del arreglo sin alterar los datos (el total de elementos debe ser igual)
- `.flatten()` → convierte cualquier arreglo multidimensional en un vector 1D
- `np.concatenate()` → une arreglos en uno solo

In [11]:
pixeles = np.arange(1, 13)  # 12 valores
print("Arreglo original:", pixeles)

# Reshape: simula una imagen de 3x4
imagen = pixeles.reshape(3, 4)
print("\nComo imagen 3x4:")
print(imagen)

# Flatten: vuelve a vector
print("\nAplanada:", imagen.flatten())

# Concatenar dos grupos de datos
grupo1 = np.array([5, 10, 15])
grupo2 = np.array([20, 25, 30])
total = np.concatenate([grupo1, grupo2])
print("\nConcatenado:", total)

Arreglo original: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Como imagen 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Aplanada: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Concatenado: [ 5 10 15 20 25 30]


## 1.10 Álgebra lineal: `np.linalg.inv()` y `np.linalg.matrix_transpose()`

- **Inversa**: `np.linalg.inv(A)` — necesaria para resolver sistemas de ecuaciones lineales (p.ej., regresión lineal exacta)
- **Transpuesta**: `np.linalg.matrix_transpose(A)` — intercambia filas por columnas

In [12]:
M = np.array([[2, 1],
              [5, 3]])

inversa = np.linalg.inv(M)
print("Matriz M:")
print(M)
print("\nInversa de M:")
print(inversa)

transpuesta = np.linalg.matrix_transpose(M)
print("\nTranspuesta de M:")
print(transpuesta)

Matriz M:
[[2 1]
 [5 3]]

Inversa de M:
[[ 3. -1.]
 [-5.  2.]]

Transpuesta de M:
[[2 5]
 [1 3]]


## 1.11 Números aleatorios: `rand`, `randint`, `randn`

Muy usados para **simulación** y para **inicializar pesos** en modelos de machine learning:
- `np.random.rand(n)` → distribución uniforme en (0, 1)
- `np.random.randint(a, b)` → entero aleatorio entre a y b-1
- `np.random.randn(n)` → distribución normal estándar (media=0, σ=1)

In [13]:
np.random.seed(42)  # Para reproducibilidad

# Simular probabilidades de 6 eventos
probabilidades = np.random.rand(6)
print("Probabilidades aleatorias:", probabilidades)

# Simular lanzamiento de dado (1 a 6)
dado = np.random.randint(1, 7)
print("Resultado de un dado:", dado)

# Simular ruido gaussiano en 5 señales
ruido = np.random.randn(5)
print("Ruido gaussiano:", ruido)

Probabilidades aleatorias: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
Resultado de un dado: 3
Ruido gaussiano: [-2.01096289 -0.49280342  0.39257975 -0.92918467  0.07983181]


## 1.12 Filtrado con condiciones y `np.where()`

- **Filtrado booleano**: `arr[arr > valor]` selecciona elementos que cumplen la condición
- **`np.where(condición, val_true, val_false)`**: aplica una condición y devuelve valores diferentes según el resultado. Equivale a un `if-else` vectorizado.

In [14]:
calificaciones = np.array([3.2, 4.5, 2.8, 3.9, 4.1, 1.5, 4.8, 3.0])

# Estudiantes que pasaron (nota >= 3.0)
aprobados = calificaciones[calificaciones >= 3.0]
print("Notas de aprobados:", aprobados)

# Notas entre 3.5 y 4.5
rango = calificaciones[(calificaciones >= 3.5) & (calificaciones <= 4.5)]
print("Notas en rango [3.5, 4.5]:", rango)

# Etiquetar: 1 si aprueba (>=3.0), 0 si no
etiquetas = np.where(calificaciones >= 3.0, 1, 0)
print("Etiqueta Aprueba/Pierde:", etiquetas)

# Reemplazar solo los que pierden por la mínima nota aprobatoria
corregidas = np.where(calificaciones >= 3.0, calificaciones, 3.0)
print("Notas con piso en 3.0:  ", corregidas)

Notas de aprobados: [3.2 4.5 3.9 4.1 4.8 3. ]
Notas en rango [3.5, 4.5]: [4.5 3.9 4.1]
Etiqueta Aprueba/Pierde: [1 1 0 1 1 0 1 1]
Notas con piso en 3.0:   [3.2 4.5 3.  3.9 4.1 3.  4.8 3. ]


---
# PARTE 2: Pandas — DataFrames y Series

In [15]:
import pandas as pd
import numpy as np

## 2.1 `pd.Series` — Vector columna con índice

Una Serie es un arreglo 1D con **índice** asociado. Es la estructura más simple de Pandas, útil para representar una variable con etiquetas.

In [16]:
# Ventas por día de la semana
ventas_diarias = pd.Series(
    [85000, 92000, 78000, 105000, 130000],
    index=['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']
)
print(ventas_diarias)

Lunes         85000
Martes        92000
Miércoles     78000
Jueves       105000
Viernes      130000
dtype: int64


## 2.2 `pd.DataFrame` — Tabla de datos

Un DataFrame es una tabla bidimensional con filas y columnas etiquetadas. Es la estructura central de Pandas, equivalente a una hoja de cálculo o una tabla de base de datos.

In [17]:
df = pd.DataFrame({
    'producto'  : ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Audífonos'],
    'categoria' : ['Computadores', 'Periféricos', 'Periféricos', 'Computadores', 'Audio'],
    'precio'    : [3500000, 85000, 120000, 950000, 250000],
    'stock'     : [15, 80, 60, 20, 45],
    'calificacion': [4.7, 4.2, 3.9, 4.5, 4.8]
})
df

,producto,categoria,precio,stock,calificacion
0,Laptop,Computadores,3500000,15,4.7
1,Mouse,Periféricos,85000,80,4.2
2,Teclado,Periféricos,120000,60,3.9
3,Monitor,Computadores,950000,20,4.5
4,Audífonos,Audio,250000,45,4.8


## 2.3 Inspección: `.head()`, `.info()`, `.describe()`, `.shape`

Son las primeras funciones que se usan al recibir un dataset:
- `.head(n)` → primeras `n` filas
- `.info()` → tipos de datos y valores nulos
- `.describe()` → estadísticas básicas de columnas numéricas
- `.shape` → (filas, columnas)

In [18]:
print("--- Primeras 3 filas ---")
print(df.head(3))

print("\n--- Información del DataFrame ---")
df.info()

print("\n--- Estadísticas descriptivas ---")
print(df.describe())

print("\nDimensiones:", df.shape)

--- Primeras 3 filas ---
  producto     categoria   precio  stock  calificacion
0   Laptop  Computadores  3500000     15           4.7
1    Mouse   Periféricos    85000     80           4.2
2  Teclado   Periféricos   120000     60           3.9

--- Información del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   producto      5 non-null      object 
 1   categoria     5 non-null      object 
 2   precio        5 non-null      int64  
 3   stock         5 non-null      int64  
 4   calificacion  5 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

--- Estadísticas descriptivas ---
             precio      stock  calificacion
count  5.000000e+00   5.000000      5.000000
mean   9.810000e+05  44.000000      4.420000
std    1.451277e+06  27.248853      0.370135
min    8.500000e+04  15.000000      3

## 2.4 Selección de columnas y filas

- `df['col']` → una sola columna como Serie
- `df[['col1', 'col2']]` → varias columnas como DataFrame
- `df[df['col'] > valor]` → filtrado de filas por condición

In [19]:
# Columna simple
print("Productos disponibles:")
print(df['producto'])

# Varias columnas
print("\nProducto y precio:")
print(df[['producto', 'precio']])

# Filtrado: productos con precio mayor a 200 000
print("\nProductos con precio > 200 000:")
print(df[df['precio'] > 200000])

# Filtrado con doble condición
print("\nProductos con calificación entre 4.2 y 4.7:")
print(df[(df['calificacion'] >= 4.2) & (df['calificacion'] <= 4.7)])

Productos disponibles:
0       Laptop
1        Mouse
2      Teclado
3      Monitor
4    Audífonos
Name: producto, dtype: object

Producto y precio:
    producto   precio
0     Laptop  3500000
1      Mouse    85000
2    Teclado   120000
3    Monitor   950000
4  Audífonos   250000

Productos con precio > 200 000:
    producto     categoria   precio  stock  calificacion
0     Laptop  Computadores  3500000     15           4.7
3    Monitor  Computadores   950000     20           4.5
4  Audífonos         Audio   250000     45           4.8

Productos con calificación entre 4.2 y 4.7:
  producto     categoria   precio  stock  calificacion
0   Laptop  Computadores  3500000     15           4.7
1    Mouse   Periféricos    85000     80           4.2
3  Monitor  Computadores   950000     20           4.5


## 2.5 Manejo de valores nulos: `isnull()`, `dropna()`, `fillna()`

Los datos reales casi siempre tienen valores faltantes. Pandas ofrece herramientas para detectarlos y tratarlos:
- `isnull()` → máscara booleana donde `True` = valor faltante
- `dropna()` → elimina filas con al menos un nulo
- `fillna()` → rellena nulos con un valor (media, mediana, constante)

In [20]:
datos_sensores = pd.DataFrame({
    'sensor'      : ['S1', 'S2', 'S3', 'S4', None],
    'temperatura' : [22.1, np.nan, 19.5, 24.3, 21.0],
    'humedad'     : [60, 55, np.nan, 70, 65],
    'presion'     : [1013, 1012, 1015, None, 1014]
})

print("DataFrame con nulos:")
print(datos_sensores)

print("\n¿Dónde hay nulos?")
print(datos_sensores.isnull())

print("\nConteo de nulos por columna:")
print(datos_sensores.isnull().sum())

# Eliminar filas con cualquier nulo
sin_nulos = datos_sensores.dropna()
print("\nSin ningún nulo:")
print(sin_nulos)

# Eliminar solo filas con nulo en 'temperatura'
sin_nulos_temp = datos_sensores.dropna(subset=['temperatura'])
print("\nEliminando solo nulos en temperatura:")
print(sin_nulos_temp)

DataFrame con nulos:
  sensor  temperatura  humedad  presion
0     S1         22.1     60.0   1013.0
1     S2          NaN     55.0   1012.0
2     S3         19.5      NaN   1015.0
3     S4         24.3     70.0      NaN
4   None         21.0     65.0   1014.0

¿Dónde hay nulos?
   sensor  temperatura  humedad  presion
0   False        False    False    False
1   False         True    False    False
2   False        False     True    False
3   False        False    False     True
4    True        False    False    False

Conteo de nulos por columna:
sensor         1
temperatura    1
humedad        1
presion        1
dtype: int64

Sin ningún nulo:
  sensor  temperatura  humedad  presion
0     S1         22.1     60.0   1013.0

Eliminando solo nulos en temperatura:
  sensor  temperatura  humedad  presion
0     S1         22.1     60.0   1013.0
2     S3         19.5      NaN   1015.0
3     S4         24.3     70.0      NaN
4   None         21.0     65.0   1014.0


In [21]:
# Rellenar nulos con la media de cada columna numérica
datos_sensores['temperatura'] = datos_sensores['temperatura'].fillna(datos_sensores['temperatura'].mean())
datos_sensores['humedad']     = datos_sensores['humedad'].fillna(datos_sensores['humedad'].mean())
datos_sensores['presion']     = datos_sensores['presion'].fillna(datos_sensores['presion'].mean())
datos_sensores['sensor']      = datos_sensores['sensor'].fillna('S_desconocido')

print("DataFrame después de fillna():")
print(datos_sensores)

DataFrame después de fillna():
          sensor  temperatura  humedad  presion
0             S1       22.100     60.0   1013.0
1             S2       21.725     55.0   1012.0
2             S3       19.500     62.5   1015.0
3             S4       24.300     70.0   1013.5
4  S_desconocido       21.000     65.0   1014.0


## 2.6 `.replace()` y `.drop_duplicates()`

- `.replace()` → reemplaza valores específicos en una columna (útil para estandarizar categorías)
- `.drop_duplicates()` → elimina filas completamente repetidas

In [22]:
pedidos = pd.DataFrame({
    'cliente'  : ['Ana', 'Luis', 'Ana', 'Sofía', 'Luis'],
    'ciudad'   : ['bogota', 'medellin', 'bogota', 'cali', 'medellin'],
    'monto'    : [150000, 220000, 150000, 95000, 220000]
})

# Estandarizar nombres de ciudades
pedidos['ciudad'] = pedidos['ciudad'].replace({
    'bogota': 'Bogotá',
    'medellin': 'Medellín',
    'cali': 'Cali'
})
print("Con ciudades normalizadas:")
print(pedidos)

# Eliminar filas duplicadas
sin_duplicados = pedidos.drop_duplicates()
print("\nSin duplicados:")
print(sin_duplicados)

Con ciudades normalizadas:
  cliente    ciudad   monto
0     Ana    Bogotá  150000
1    Luis  Medellín  220000
2     Ana    Bogotá  150000
3   Sofía      Cali   95000
4    Luis  Medellín  220000

Sin duplicados:
  cliente    ciudad   monto
0     Ana    Bogotá  150000
1    Luis  Medellín  220000
3   Sofía      Cali   95000


## 2.7 Nuevas columnas, `.apply()` con `lambda` y `.rename()`

- Se puede crear una nueva columna con una operación directa sobre columnas existentes
- `.apply(lambda x: ...)` permite aplicar cualquier función a cada elemento
- `.rename()` cambia el nombre de columnas

In [23]:
empleados = pd.DataFrame({
    'id'        : [101, 102, 103, 104],
    'nombre'    : ['Laura Gómez', 'Andrés Pérez', 'Juliana Ruiz', 'Carlos Díaz'],
    'salario'   : [2800000, 3500000, 4200000, 3100000],
    'horas_extra': [10, 5, 0, 8]
})

# Nueva columna: salario anual
empleados['salario_anual'] = empleados['salario'] * 12

# Con lambda: bonificación por horas extra
empleados['bonificacion'] = empleados['horas_extra'].apply(lambda h: h * 15000)

# Renombrar columna
empleados = empleados.rename(columns={'horas_extra': 'horas_adicionales'})

print(empleados)

    id        nombre  salario  horas_adicionales  salario_anual  bonificacion
0  101   Laura Gómez  2800000                 10       33600000        150000
1  102  Andrés Pérez  3500000                  5       42000000         75000
2  103  Juliana Ruiz  4200000                  0       50400000             0
3  104   Carlos Díaz  3100000                  8       37200000        120000


## 2.8 Manipulación de texto: `.str.upper()`, `.str.strip()`, `.str.replace()`

El accessor `.str` permite aplicar operaciones de cadena a toda una columna de texto de forma vectorizada, sin necesidad de loops.

In [24]:
# Limpiar y estandarizar la columna 'nombre'
empleados['nombre'] = empleados['nombre'].str.upper()        # mayúsculas
empleados['nombre'] = empleados['nombre'].str.strip()        # eliminar espacios extremos
empleados['nombre'] = empleados['nombre'].str.replace('DÍAZ', 'DIAZ')  # normalizar tildes

print("Nombres estandarizados:")
print(empleados[['id', 'nombre']])

Nombres estandarizados:
    id        nombre
0  101   LAURA GÓMEZ
1  102  ANDRÉS PÉREZ
2  103  JULIANA RUIZ
3  104   CARLOS DIAZ


## 2.9 `groupby()` y `sort_values()`

- `groupby()` → agrupa filas por una columna y aplica una función de agregación (media, suma, conteo, etc.). Equivale a un `GROUP BY` de SQL.
- `sort_values()` → ordena el DataFrame por una o más columnas.

In [25]:
ventas_df = pd.DataFrame({
    'vendedor'  : ['Ana', 'Luis', 'Ana', 'Sofía', 'Luis', 'Sofía'],
    'region'    : ['Norte', 'Sur', 'Sur', 'Norte', 'Norte', 'Sur'],
    'venta'     : [500000, 320000, 410000, 680000, 290000, 540000]
})

# Venta promedio por vendedor
por_vendedor = ventas_df.groupby('vendedor')['venta'].mean()
print("Venta promedio por vendedor:")
print(por_vendedor)

# Ordenar por venta de mayor a menor
ordenado = ventas_df.sort_values(by='venta', ascending=False)
print("\nVentas ordenadas de mayor a menor:")
print(ordenado)

Venta promedio por vendedor:
vendedor
Ana      455000.0
Luis     305000.0
Sofía    610000.0
Name: venta, dtype: float64

Ventas ordenadas de mayor a menor:
  vendedor region   venta
3    Sofía  Norte  680000
5    Sofía    Sur  540000
0      Ana  Norte  500000
2      Ana    Sur  410000
1     Luis    Sur  320000
4     Luis  Norte  290000


## 2.10 Conversión entre NumPy y Pandas: `.values` y `pd.DataFrame(arr)`

Es frecuente necesitar pasar de un DataFrame a un array de NumPy (para alimentar modelos de ML) y viceversa (para mostrar resultados como tabla).

In [26]:
# DataFrame → ndarray de NumPy
matriz_ventas = ventas_df[['venta']].values
print("Como array NumPy:")
print(matriz_ventas)
print("Tipo:", type(matriz_ventas))

# ndarray de NumPy → DataFrame
datos_np = np.array([[1, 100], [2, 200], [3, 150]])
df_desde_np = pd.DataFrame(datos_np, columns=['semana', 'pedidos'])
print("\nDesde NumPy a DataFrame:")
print(df_desde_np)

Como array NumPy:
[[500000]
 [320000]
 [410000]
 [680000]
 [290000]
 [540000]]
Tipo: <class 'numpy.ndarray'>

Desde NumPy a DataFrame:
   semana  pedidos
0       1      100
1       2      200
2       3      150


## 2.11 Cálculo sobre columnas: `.mean()`, `.value_counts()`

- `.mean()` directamente sobre una columna calcula el promedio
- `.value_counts()` cuenta cuántas veces aparece cada valor único en una columna categórica

In [27]:
precio_promedio = df['precio'].mean()
print(f"Precio promedio del catálogo: ${precio_promedio:,.0f}")

conteo_categorias = df['categoria'].value_counts()
print("\nProductos por categoría:")
print(conteo_categorias)

Precio promedio del catálogo: $981,000

Productos por categoría:
categoria
Computadores    2
Periféricos     2
Audio           1
Name: count, dtype: int64


---
# PARTE 3: NumPy y Pandas en Ciencia de Datos
## Uso, Ventajas y Desventajas para Implementar Algoritmos


##  NumPy en Ciencia de Datos

### ¿Para qué se usa?

NumPy es el **fundamento numérico** del ecosistema científico de Python. Prácticamente todas las bibliotecas de ML (scikit-learn, TensorFlow, PyTorch) operan internamente sobre arrays de NumPy.

Sus principales usos en ciencia de datos son:

1. **Preprocesamiento numérico**: normalización, escalado, transformación de variables antes de entrenar un modelo.
2. **Operaciones matriciales**: multiplicación de matrices, cálculo de gradientes, inversión de matrices (regresión lineal).
3. **Generación de datos sintéticos**: simulaciones y datos de prueba usando distribuciones estadísticas.
4. **Implementación manual de algoritmos**: descenso del gradiente, k-means, PCA desde cero.

---

### Ventajas de NumPy

| Ventaja | Descripción |
|---|---|
| **Velocidad** | Implementado en C; hasta 50× más rápido que listas de Python para cálculos numéricos. |
| **Eficiencia de memoria** | Los arrays homogéneos (`ndarray`) consumen mucho menos RAM que listas equivalentes. |
| **Vectorización** | Elimina la necesidad de bucles `for` explícitos; el código es más corto y más rápido. |
| **Algebra lineal completa** | Funciones para inversas, determinantes, descomposición SVD, eigenvalores, etc. |
| **Interoperabilidad** | Es la base de Pandas, Matplotlib, SciPy, scikit-learn, TensorFlow y PyTorch. |
| **Broadcasting** | Permite operar arreglos de formas distintas sin copiar datos (p.ej. sumar un escalar a una matriz). |

---

###  Desventajas de NumPy

| Desventaja | Descripción |
|---|---|
| **Tipos homogéneos** | Todos los elementos deben ser del mismo tipo; no soporta columnas mixtas (texto + números) directamente. |
| **Sin índice ni etiquetas** | Los arreglos no tienen nombres de columna ni índices con significado; el acceso es solo por posición numérica. |
| **Sin soporte nativo de NaN para enteros** | Los valores faltantes (`NaN`) obligan a convertir arrays enteros a `float`, aumentando el uso de memoria. |
| **No apto para datos tabulares complejos** | Para manipular tablas con columnas heterogéneas, se necesita Pandas. |
| **Operaciones en datos no numéricos** | No puede manejar cadenas de texto o fechas de forma natural. |

## Pandas en Ciencia de Datos

### ¿Para qué se usa?

Pandas es la herramienta estándar para el **análisis exploratorio y limpieza de datos** (EDA). Opera sobre datos tabulares heterogéneos (texto, números, fechas mezclados) y forma el puente entre los datos crudos y los modelos de ML.

Sus usos principales son:

1. **Ingestión de datos**: leer CSV, Excel, JSON, SQL, Parquet.
2. **Limpieza**: manejo de nulos, duplicados, inconsistencias y formatos.
3. **Feature engineering**: crear nuevas variables derivadas, codificación de categóricas.
4. **Análisis descriptivo**: agrupaciones, pivotes, correlaciones, estadísticas.
5. **Preparación del dataset**: dividir, filtrar y exportar datos hacia modelos.

---

###  Ventajas de Pandas

| Ventaja | Descripción |
|---|---|
| **Datos heterogéneos** | Soporta columnas de distintos tipos (int, float, str, datetime) en una misma tabla. |
| **Índices con etiquetas** | Las filas y columnas tienen nombres, haciendo el acceso más claro y legible. |
| **Limpieza de datos** | `fillna`, `dropna`, `replace`, `drop_duplicates` simplifican enormemente el tratamiento de datos sucios. |
| **Integración con el ecosistema** | Lee/escribe CSV, Excel, JSON, SQL, Parquet; se integra con matplotlib, seaborn, scikit-learn. |
| **Operaciones tipo SQL** | `groupby`, `merge`, `join`, `pivot_table` permiten análisis de datos avanzado sin salir de Python. |
| **Curva de aprendizaje suave** | Su API es intuitiva para quienes vienen de Excel o SQL. |

---

###  Desventajas de Pandas

| Desventaja | Descripción |
|---|---|
| **Limitado para Big Data** | Todos los datos deben cargarse en RAM; con datasets de varios GB el rendimiento cae drásticamente. |
| **Un solo hilo (single-threaded)** | La mayoría de operaciones no aprovechan múltiples núcleos del procesador. |
| **Alto consumo de memoria** | Pandas puede requerir de 5 a 10× la memoria del archivo original al cargarlo, por sus estructuras internas. |
| **Operaciones numéricas más lentas que NumPy** | Para cálculos matriciales, es menos eficiente que NumPy puro; se recomienda convertir a `ndarray`. |
| **Inconsistencias en la API** | Algunas funciones como `loc`, `iloc`, `at`, `iat` pueden confundir a principiantes. |
| **No escala horizontalmente** | No está diseñado para computación distribuida; para eso existen PySpark, Dask o Polars. |

##  Comparación General: ¿Cuándo usar cada uno?

| Situación | Herramienta recomendada |
|---|---|
| Operaciones algebraicas / matriciales (regresión, redes neuronales) | **NumPy** |
| Limpieza y exploración de datos tabulares | **Pandas** |
| Inicializar parámetros de un modelo | **NumPy** |
| Cargar un CSV y hacer EDA | **Pandas** |
| Alimentar un modelo de scikit-learn | **Pandas** → convertir a **NumPy** con `.values` |
| Dataset > 10 GB en RAM | Considerar **Polars**, **Dask** o **PySpark** |
| Simulaciones estadísticas | **NumPy** |
| Agrupar, unir y pivotar tablas | **Pandas** |

---

> Por lo tanto yo concluyo que NumPy y Pandas son complementarias, no competidoras. En un flujo de trabajo real de ciencia de datos, Pandas se usa en las etapas de **ingesta, limpieza y exploración**, y NumPy en las etapas de **cálculo numérico y modelado**. Dominar ambas es una habilidad fundamental para cualquier científico de datos.

---
*Fuentes consultadas: ENAE Business School, Universidad Europea de Madrid, Estudyando.com, Databricks Blog, JetBrains PyCharm Blog, Aprender Big Data — 2024/2026.*